### ISSUE TITLE
Make KubeVirt tasks available on Tekton Hub

### ISSUE THREAD

**Issue by tylerauerbeck** [kubevirt/kubevirt-tekton-tasks#100]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
It would be easier to discover these tasks if they were available on the Tekton Hub (hub.tekton.dev) and may even drive the creation of additional tasks

**What you expected to happen**:
Search for KubeVirt tekton tasks on the tekton hub and see that they exist.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Comment by ksimon1** [comment]
KubeVirt tekton tasks are now available on Artifact hub
https://artifacthub.io/packages/search?org=kubevirt&sort=relevance&page=1
