### ISSUE TITLE
Pipeline keeps running when copy-template Task fails

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt-tekton-tasks#139]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

`copy-template` Task failed because the template it tried to create already existed. After that the Pipeline stayed in state `Running`.

**What you expected to happen**:

The Pipeline switches to state `Failed` when `copy-template` Task failed.

**How to reproduce it (as minimally and precisely as possible)**:

- Create template (e.g. with name `testtemplate`)
- Run `copy-template` Task with parameter `targetTemplateName` set to `testtemplate`

**Comment by opokornyy** [comment]
I have been testing this behavior and what I have come to is that if you do not force any order of tasks then ```copy-template``` task fails, but tasks after that will be still executed and ```Pipelinerun``` will be in state ```Failed```.

When I have forced task ```copy-template``` to be executed before other tasks in pipeline, for example by adding to other tasks:

 ```runafter:  - copy-template``` 
 
 than the log looked like this:
```[copy-template : copytemplate] 2022/06/17 07:29:43 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/": unable to create destination directory: mkdir /.docker: permission denied
[copy-template : copytemplate] templates.template.openshift.io "testtemplate-copied" already exists

Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 1
```
And pipeline was in state "Failed" and did not keep executing tasks after ```copy-template``` task, which seems to me as a correct behavior. Please let me know if this worked for you or if I misunderstood the issue.

**Comment by opokornyy** [comment]
@0xFelix

**Comment by 0xFelix** [comment]
Your description is correct and the behavior seems correct to me. It is working for me now and I can't reproduce the issue, thank you.
