### ISSUE TITLE
windows-efi-installer pipelinerun fails with permission denied on step "modify-windows-iso-file"

### ISSUE THREAD

**Issue by johwes** [kubevirt/kubevirt-tekton-tasks#427]
**What happened**:
I want to install and use the tekton tasks to run the example pipeline,
Windows EFI Installer Pipeline
When instantiating the pipelinerun as part of,
https://github.com/kubevirt/kubevirt-tekton-tasks/blob/main/release/pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml

The task "modify-windows-iso-file" fails.
Log output states permission denied

**What you expected to happen**:
I expect the pipeline to complete and having a working Windows Template.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the install section on the main Readme.
Create the pipeline,
kubevirt-tekton-tasks/release/pipelines/windows-efi-installer
and instanciate a pipelinerun

**Additional context**:
I believe the problem is because the pipelinerun defines some values to the podtemplate,
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001     
See,
https://github.com/kubevirt/kubevirt-tekton-tasks/blob/main/release/pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml

Changing this to
  taskRunSpecs:
    - pipelineTaskName: "modify-windows-iso-file"
      podTemplate:
        securityContext:
          runAsUser: 107 
          runAsGroup: 1001
          fsGroup: 107     

Makes the pipeline work.
**Environment**:
- KubeVirt version (use `virtctl version`): N/A
Client Version: version.Info{GitVersion:"v1.1.1-110-g359e3f5ed", GitCommit:"359e3f5eda4ad2c77958b98924ed9a1e53c91d06", GitTreeState:"clean", BuildDate:"2024-05-29T01:45:44Z", GoVersion:"go1.20.12 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.1.1-110-g359e3f5ed", GitCommit:"359e3f5eda4ad2c77958b98924ed9a1e53c91d06", GitTreeState:"clean", BuildDate:"2024-06-07T04:25:34Z", GoVersion:"go1.20.12 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): N/A
Client Version: 4.15.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Kubernetes Version: v1.28.6+6216ea1

- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by johwes** [comment]
Here is log output of a failed run,

Defaulted container "step-modify-iso-file" out of: step-modify-iso-file, step-create-iso-file, step-convert-iso-file, prepare (init), place-scripts (init)
+ export LIBGUESTFS_PATH=/usr/local/lib/guestfs/appliance
+ LIBGUESTFS_PATH=/usr/local/lib/guestfs/appliance
+ export ISO_FILES_PATH=/tmp/extracted-iso-files
+ ISO_FILES_PATH=/tmp/extracted-iso-files
+ export EFI_BOOT=/tmp/extracted-iso-files/efi/microsoft/boot
+ EFI_BOOT=/tmp/extracted-iso-files/efi/microsoft/boot
+ export TARGET_IMG_FILE_PATH=tmp/target-pvc/disk.img
+ TARGET_IMG_FILE_PATH=tmp/target-pvc/disk.img
+ guestfish -a tmp/target-pvc/disk.img -m /dev/sda tar-out / -
++ id -u
++ id -g
+ tar xvf - -C /tmp/extracted-iso-files -m --no-overwrite-dir --owner=1001 --group=1001 --no-same-permissions
guestfish: access: tmp/target-pvc/disk.img: Permission denied
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
+ '[' '!' -f /tmp/extracted-iso-files/efi/microsoft/boot/efisys_noprompt.bin ']'
+ echo '/tmp/extracted-iso-files/efi/microsoft/boot/efisys_noprompt.bin or /tmp/extracted-iso-files/efi/microsoft/boot/cdboot_noprompt.efi not found in the iso file! Task expects that ISO file contains bootloader without prompt. If the no prompt bootloader is not present, the installation might behave unexpectedly. Exiting'
/tmp/extracted-iso-files/efi/microsoft/boot/efisys_noprompt.bin or /tmp/extracted-iso-files/efi/microsoft/boot/cdboot_noprompt.efi not found in the iso file! Task expects that ISO file contains bootloader without prompt. If the no prompt bootloader is not present, the installation might behave unexpectedly. Exiting
++ sha256sum tmp/target-pvc/disk.img
sha256sum: tmp/target-pvc/disk.img: Permission denied
ISO file checksum:
+ echo 'ISO file checksum:'
+ ls -la tmp/target-pvc/disk.img
-rw-rw----. 1 107 99 9662627840 Jun 12 11:11 tmp/target-pvc/disk.img
+ exit 1

**Comment by ksimon1** [comment]
Hi @johwes, 
thanks for reporting this. The problem is that on some storages the UID and GID of the files / folders are not set correctly to mounted PVCs (mostly this happens on NFS). If user runs the PipelineRun without 
```
    taskRunSpecs:
    -   pipelineTaskName: modify-windows-iso-file
        podTemplate:
        ...
```
then the disk will have different IDs and guestfish will get the permission denied error. 
The fix for it is to run the pipelinerun with the taskRunSpecs as described here: https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/release/pipelines/windows-efi-installer#common-errors (it should not matter if the ids are 1001 or 107)

**Comment by johwes** [comment]
Great stuff!
I think the new comment on common-errors is clear and the example now works.
I'm glad to close the issue.
Thank you!
