### ISSUE TITLE
add multi namespace example pipeline

### ISSUE THREAD

**Issue by atiratree** [kubevirt/kubevirt-tekton-tasks#65]
create an example pipeline which use concepts explained in https://github.com/kubevirt/kubevirt-tekton-tasks/blob/main/docs/tasks-rbac-permissions.md 

- the pipeline should access/create resources in different namespaces
- the pipeline should explain on how to deploy and setup the tasks/namespaces for this pipeline

**Comment by ksimon1** [comment]
Closing, as we already have a multi namespace pipeline example https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/examples/pipelines/windows10-installer
