### ISSUE TITLE
Downstream related information should be removed

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt-tekton-tasks#86]
https://github.com/kubevirt/kubevirt-tekton-tasks/blame/main/README.md#L24-L34

We should not maintain downstream documentation

**Comment by suomiy** [comment]
Do you mean renaming it to OKD or removing it?

**Comment by mazzystr** [comment]
At the very least changing it to OKD.

My vote is removing it completely since [Rancher k3s](https://rancher.com/products/k3s/) or [SuSe Casp](https://www.suse.com/c/introducing-suse-containers-service-platform/) is not mentioned.  See how fast we go down the conflict of interest slope even mentioning one downstream?

**Comment by suomiy** [comment]
Ok, I will change it to OKD mainly because we are implementing an OKD/OpenShift task: https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/tasks/create-vm-from-template and need a specific installation manifest for that

**Comment by mazzystr** [comment]
OKD is a fair compromise
